[project]
name = "tsetlin-machine-py"
version = "1.0.0"
description = "C library for Tsetlin Machines."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flatbuffers>=25.2.10",
    "green-tsetlin>=1.0.1",
    "numpy>=2.2.5",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
]
